### PR TITLE
Recipe improvements

### PR DESCRIPTION
**Pull request by Anthchirp**
* ensures the upstream and downstream python environments are consistent
* build scripts stop when an error is encountered

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Anthchirp** [comment]
@conda-forge-admin, please rerender

**Comment by Anthchirp** [comment]
mac builds failing due to https://github.com/conda-forge/clangdev-feedstock/issues/115

**Comment by bkpoon** [comment]
I added a patch to look for the compilers with some other environment variable in #9. I can merge this after that one is merged.

**Comment by Anthchirp** [comment]
@conda-forge-admin please restart ci

**Comment by Anthchirp** [comment]
> I added a patch to look for the compilers with some other environment variable in #9. I can merge this after that one is merged.

not necessary, I've fixed the compiler package upstream.

This is ready for merging.

**Review by bkpoon — APPROVED** [review]

**Pull request merged**
